name: Validate pull request
on:
  pull_request:
    branches:
      - main
jobs:
  plan:
    strategy:
      matrix:
        environment:
          - nsccluster
    name: Plan ${{ matrix.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Splat PEM
        shell: bash
        id: splatpem
        run: |
          export TMPPEM="$(mktemp)"
          echo "${{ secrets.OCI_PJNP_PEM }}" >> ${TMPPEM}
          echo "PEM_PATH=${TMPPEM}" >> ${GITHUB_OUTPUT}
      - name: Plan
        uses: catalystsquad/action-terraform@v1
        with:
          command: plan
          work-dir: ${{ matrix.environment }}
        env:
          TF_VAR_tenancy_ocid: ${{ secrets.OCI_PJ_TENANCY_OCID }}
          TF_VAR_user_ocid: ${{ secrets.OCI_PJ_USER_OCID }}
          TF_VAR_fingerprint: ${{ secrets.OCI_PJNP_FINGERPRINT }}
          TF_VAR_private_key_path: ${{ steps.splatpem.outputs.PEM_PATH }}
          TF_VAR_region: ${{ secrets.OCI_PJNP_REGION }}
      - name: Cleanup PEM
        if: always()
        shell: bash
        run: |
          rm -f ${{ steps.splatpem.outputs.PEM_PATH }}
